# Generated by Django 4.2.1 on 2023-09-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0047_userfaceencoding"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalprofile",
            name="sbev_campus",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Choose..."),
                    ("Flint, MI", "flint"),
                    ("Chicago, IL", "chicago"),
                ],
                max_length=50,
            ),
        ),
    ]
