# Generated by Django 4.2.1 on 2023-09-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0048_personalprofile_sbev_campus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalprofile",
            name="sbev_campus",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Choose..."),
                    ("Flint, MI", "Flint, MI"),
                    ("Chicago, IL", "Chicago, IL"),
                ],
                max_length=50,
            ),
        ),
    ]
