# Generated by Django 4.2.1 on 2023-09-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0022_reply_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="name",
            field=models.CharField(
                choices=[
                    ("unit1", "Unit 1: Introduction to Girl Code and Team Building"),
                    ("unit2", "Unit 2: Self-Expression Through Art"),
                    ("unit3", "Unit 3: Exploring Technology"),
                    ("unit4", "Unit 4: Digital Storytelling"),
                    ("unit5", "Unit 5: Leadership and Public Speaking"),
                    ("unit6", "Unit 6: Cultural Celebrations and Identity"),
                    ("unit7", "Unit 7: Technology and Art Fusion"),
                    ("unit8", "Unit 8: Social Justice and Advocacy"),
                    ("unit9", "Unit 9: Mentorship and Future Goals"),
                    ("unit10", "Unit 10: Showcase and Celebration"),
                ],
                max_length=200,
            ),
        ),
    ]
