# Generated by Django 4.2.1 on 2023-10-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0024_gradeassignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradeassignment",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("-", "-"),
                    ("A+", "A+"),
                    ("A", "A"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B", "B"),
                    ("B-", "B-"),
                    ("C+", "C+"),
                    ("C", "C"),
                    ("C-", "C-"),
                    ("D+", "D+"),
                    ("D", "D"),
                    ("D-", "D-"),
                    ("F", "F"),
                ],
                max_length=5,
                null=True,
            ),
        ),
    ]
