# Generated by Django 4.2.1 on 2023-10-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0025_alter_gradeassignment_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="unit_image",
            field=models.ImageField(blank=True, null=True, upload_to="unit_images/"),
        ),
    ]
