# Generated by Django 4.2.1 on 2023-10-23 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0026_unit_unit_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
    ]
