# Generated by Django 4.2.1 on 2023-11-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0029_assignment_submission"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission",
            old_name="is_approved",
            new_name="is_accepted",
        ),
        migrations.AddField(
            model_name="assignment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="assignment",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
