# Generated by Django 4.2.1 on 2023-11-02 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0030_rename_is_approved_submission_is_accepted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="due_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
