# Generated by Django 4.2.1 on 2023-11-08 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0032_alter_assignment_unit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={"ordering": ["created_at"]},
        ),
    ]
