# Generated by Django 4.2.1 on 2023-11-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0033_alter_assignment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["created_at"]},
        ),
    ]
