# Generated by Django 4.2.1 on 2023-11-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0035_submission_admin_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("-", "-"),
                    ("A+", "A+"),
                    ("A", "A"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B", "B"),
                    ("B-", "B-"),
                    ("C+", "C+"),
                    ("C", "C"),
                    ("C-", "C-"),
                    ("D+", "D+"),
                    ("D", "D"),
                    ("D-", "D-"),
                    ("F", "F"),
                ],
                default="-",
                max_length=3,
            ),
        ),
    ]
