# Generated by Django 4.2.1 on 2023-11-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0036_submission_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_review", "Pending Review"),
                    ("needs_action", "Needs Further Action"),
                    ("accepted", "Accepted"),
                ],
                default="pending_review",
                max_length=20,
            ),
        ),
    ]
