# Generated by Django 4.2.1 on 2023-11-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0037_submission_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="resubmitted_count",
            field=models.IntegerField(default=0),
        ),
    ]
