# Generated by Django 4.2.1 on 2023-11-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0038_submission_resubmitted_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_review", "Pending Review"),
                    ("needs_action", "Needs Further Action"),
                    ("accepted", "Accepted"),
                    ("revised", "Submission Revised"),
                ],
                default="pending_review",
                max_length=20,
            ),
        ),
    ]
