# Generated by Django 4.2.1 on 2023-11-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0039_alter_submission_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="token_tx_hash",
            field=models.CharField(
                blank=True,
                max_length=66,
                null=True,
                verbose_name="Token Transaction Hash",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="tokens_sent",
            field=models.IntegerField(default=0, verbose_name="Tokens Sent"),
        ),
    ]
