# Generated by Django 4.2.1 on 2023-09-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webcamrecognition", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webcamsession",
            name="face_recognized",
            field=models.BooleanField(default=False),
        ),
    ]
